// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QuYCcUR8BzeXuV4a47nrFB4JHxk42zs',
    appId: '1:1019028710180:web:f73870cc4e15e6f8cb89b1',
    messagingSenderId: '1019028710180',
    projectId: 'nusantara-recipe',
    authDomain: 'nusantara-recipe.firebaseapp.com',
    storageBucket: 'nusantara-recipe.appspot.com',
    measurementId: 'G-MGW0D3S8LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-eBpUgDP7mxDKiISyyIDQiU_b1twUlw0',
    appId: '1:1019028710180:android:b2ca85cd5ba09a79cb89b1',
    messagingSenderId: '1019028710180',
    projectId: 'nusantara-recipe',
    storageBucket: 'nusantara-recipe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0DGOrwKpL1-7CGkaIUxA1MGVObYf8tI',
    appId: '1:1019028710180:ios:1a5182c70d834dc3cb89b1',
    messagingSenderId: '1019028710180',
    projectId: 'nusantara-recipe',
    storageBucket: 'nusantara-recipe.appspot.com',
    iosBundleId: 'com.example.nusantaraRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0DGOrwKpL1-7CGkaIUxA1MGVObYf8tI',
    appId: '1:1019028710180:ios:1a5182c70d834dc3cb89b1',
    messagingSenderId: '1019028710180',
    projectId: 'nusantara-recipe',
    storageBucket: 'nusantara-recipe.appspot.com',
    iosBundleId: 'com.example.nusantaraRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-QuYCcUR8BzeXuV4a47nrFB4JHxk42zs',
    appId: '1:1019028710180:web:9ba2e89f9931ddc6cb89b1',
    messagingSenderId: '1019028710180',
    projectId: 'nusantara-recipe',
    authDomain: 'nusantara-recipe.firebaseapp.com',
    storageBucket: 'nusantara-recipe.appspot.com',
    measurementId: 'G-BMVB3JDF0H',
  );
}
